### PR TITLE
Rubocop

### PR DESCRIPTION
**Pull request by namanh1997**
Screenshot from 2019-07-17 13-33-46
ready

### CODE REVIEW

**Comment by namanh1997** [comment]
ready

**Comment by vanvtt-0952** [comment]
commented
conflict code nhé gái ơi

**Comment by namanh1997** [comment]
ready

**Comment by vanvtt-0952** [comment]
commented
sao 2 commit ri chú

**Comment by namanh1997** [comment]
ready

**Comment by vanvtt-0952** [comment]
commented
sao 2 commit ri chú =>>> còn nguyên luôn mà ready ah, chú chưa push lên ah?

**Comment by namanh1997** [comment]
ready

**Pull request merged**
